/**
 * src/config/kpiRules.js
 * UNICA FONTE DI VERITÀ per le regole KPI (formule, target, settori)
 * Usato da: KpiChartsModal, KpiLaserModal, KpiDashboardModal, KpiXrayModal
 */

export const KPI_RULES = [
  { indicatore: 'Ospiti assistiti nel mese', settore: 'ECONOMICO', calcolo: '[OSPITI ASSISTITI NEL MESE] / [POSTI LETTO ATTIVI]', kpi_target: 'Turn Over', target_verde: 0.98, target_rosso: 0.9, direzione: 'MAX' },
  { indicatore: 'Ospiti inviati al PS', settore: 'PS', calcolo: '[OSPITI INVIATI AL PS] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'Invii PS', target_verde: 0.01, target_rosso: 0.05, direzione: 'MIN' },
  { indicatore: 'Valutazione del dolore', settore: 'SANITARI', calcolo: '[VALUTAZIONE DEL DOLORE] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'Val Dolore', target_verde: 1.0, target_rosso: 0.9, direzione: 'MAX' },
  { indicatore: 'Ricoveri in seguito ad invio in PS', settore: 'PS', calcolo: '[RICOVERI IN SEGUITO AD INVIO IN PS] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'Ricoveri da PS', target_verde: 0.95, target_rosso: 0.8, direzione: 'MAX' },
  { indicatore: 'Rilevazione parametri quindicinale', settore: 'SANITARI', calcolo: '[RILEVAZIONE PARAMETRI QUINDICINALE] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'Parametri 15gg', target_verde: 0.95, target_rosso: 0.9, direzione: 'MAX' },
  { indicatore: 'Numero ospiti con lesioni da pressione in trattamento', settore: 'LESIONI', calcolo: '[NUMERO OSPITI CON LESIONI DA PRESSIONE IN TRATTAMENTO] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'Ospiti con Lesioni', target_verde: 0.01, target_rosso: 0.05, direzione: 'MIN' },
  { indicatore: 'Numero lesioni da pressione in trattamento', settore: 'LESIONI', calcolo: '[NUMERO LESIONI DA PRESSIONE IN TRATTAMENTO] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'Lesioni', target_verde: 0.01, target_rosso: 0.05, direzione: 'MIN' },
  { indicatore: 'Numero lesioni da pressione superiori al III stadio', settore: 'LESIONI', calcolo: '[NUMERO LESIONI DA PRESSIONE SUPERIORI AL III STADIO] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'Lesioni > III Stadio', target_verde: 0.01, target_rosso: 0.05, direzione: 'MIN' },
  { indicatore: 'Numero lesioni da pressione insorte in struttura', settore: 'LESIONI', calcolo: '[NUMERO LESIONI DA PRESSIONE INSORTE IN STRUTTURA] / [NUMERO LESIONI DA PRESSIONE IN TRATTAMENTO]', kpi_target: 'Lesioni Insorte', target_verde: 0.1, target_rosso: 0.15, direzione: 'MIN' },
  { indicatore: 'Lesioni da pressione guarite', settore: 'LESIONI', calcolo: '[LESIONI DA PRESSIONE GUARITE] / [NUMERO LESIONI DA PRESSIONE IN TRATTAMENTO]', kpi_target: 'Lesioni Guarite', target_verde: null, target_rosso: null, direzione: null },
  { indicatore: 'Ospiti caduti', settore: 'CADUTE', calcolo: '[OSPITI CADUTI] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'Ospiti Caduti', target_verde: 0.45, target_rosso: 0.5, direzione: 'MIN' },
  { indicatore: 'Cadute totali', settore: 'CADUTE', calcolo: '[CADUTE TOTALI] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'Cadute Totali', target_verde: 0.01, target_rosso: 0.05, direzione: 'MIN' },
  { indicatore: 'Cadute gravi', settore: 'CADUTE', calcolo: '[CADUTE GRAVI] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'Cadute Gravi', target_verde: 0.03, target_rosso: 0.05, direzione: 'MIN' },
  { indicatore: 'Cadute con invio in Pronto Soccorso', settore: 'PS', calcolo: '[CADUTE CON INVIO IN PRONTO SOCCORSO] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'Cadute invio PS', target_verde: 0.1, target_rosso: 0.15, direzione: 'MIN' },
  { indicatore: 'Mortalita', settore: 'NUMERI', calcolo: '[MORTALITA]', kpi_target: 'Morti', target_verde: 0.1, target_rosso: 0.3, direzione: 'MIN' },
  { indicatore: 'Morti inattese', settore: 'NUMERI', calcolo: '[MORTI INATTESE]', kpi_target: 'Morti Inattese', target_verde: 0.1, target_rosso: 0.3, direzione: 'MIN' },
  { indicatore: 'Errore gestione farmaci', settore: 'NUMERI', calcolo: '[ERRORE GESTIONE FARMACI]', kpi_target: 'Errori Farmaci', target_verde: 0.1, target_rosso: 0.3, direzione: 'MIN' },
  { indicatore: 'numero farmaci mediamente assunti in una giornata campione', settore: 'NUMERI', calcolo: '[NUMERO FARMACI MEDIAMENTE ASSUNTI IN UNA GIORNATA CAMPIONE] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'Farmaci Die', target_verde: 0.05, target_rosso: 0.13, direzione: 'MIN' },
  { indicatore: 'numero ospiti con almeno una contenzione prescritta', settore: 'CONTENZIONI', calcolo: '[NUMERO OSPITI CON ALMENO UNA CONTENZIONE PRESCRITTA] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'Contenzioni', target_verde: 0.01, target_rosso: 0.05, direzione: 'MIN' },
  { indicatore: 'numero ospiti con solo spondine a letto', settore: 'CONTENZIONI', calcolo: '[NUMERO OSPITI CON SOLO SPONDINE A LETTO] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'Cont. solo Spondine', target_verde: 0.01, target_rosso: 0.05, direzione: 'MIN' },
  { indicatore: 'Ospiti con valutazione stato nutrizionale', settore: 'SANITARI', calcolo: '[OSPITI CON VALUTAZIONE STATO NUTRIZIONALE] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'Val. Nutrizionale', target_verde: 0.95, target_rosso: 0.9, direzione: 'MAX' },
  { indicatore: 'numero ospiti valutati a rischio malnutrizione / disidratazione', settore: 'ASSISTENZA', calcolo: '[NUMERO OSPITI VALUTATI A RISCHIO MALNUTRIZIONE / DISIDRATAZIONE] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'Rischio Malnutrizione', target_verde: null, target_rosso: null, direzione: null },
  { indicatore: 'numero ospiti con disfagia', settore: 'ASSISTENZA', calcolo: '[NUMERO OSPITI CON DISFAGIA] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'Disfagia', target_verde: null, target_rosso: null, direzione: null },
  { indicatore: 'numero ospiti che necessitano di assistenza per essere alimentati', settore: 'ASSISTENZA', calcolo: '[NUMERO OSPITI CHE NECESSITANO DI ASSISTENZA PER ESSERE ALIMENTATI] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'Assistenza Alim.', target_verde: null, target_rosso: null, direzione: null },
  { indicatore: 'numero ospiti con alimentazione enterale con sonda', settore: 'ASSISTENZA', calcolo: '[NUMERO OSPITI CON ALIMENTAZIONE ENTERALE CON SONDA] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'Alim. Sonda', target_verde: null, target_rosso: null, direzione: null },
  { indicatore: 'Numero ospiti con incontinenza (singola o doppia)', settore: 'ASSISTENZA', calcolo: '[NUMERO OSPITI CON INCONTINENZA (SINGOLA O DOPPIA)] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'Incontinenza', target_verde: null, target_rosso: null, direzione: null },
  { indicatore: 'Ospiti con PI PAI redatto entro 30 gg dall ingresso', settore: 'COMPLIANCE', calcolo: '[OSPITI CON PI PAI REDATTO ENTRO 30 GG DALL INGRESSO] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'PI PAI 30gg', target_verde: 0.95, target_rosso: 0.9, direzione: 'MAX' },
  { indicatore: 'Ospiti con PI PAI aggiornato entro 180 gg', settore: 'COMPLIANCE', calcolo: '[OSPITI CON PI PAI AGGIORNATO ENTRO 180 GG] / [OSPITI ASSISTITI NEL MESE]', kpi_target: 'PI PAI 180gg', target_verde: 0.95, target_rosso: 0.9, direzione: 'MAX' },
  { indicatore: 'numero segnalazioni per reclami aperte nel mese', settore: 'ISPEZIONI', calcolo: '[NUMERO SEGNALAZIONI PER RECLAMI APERTE NEL MESE]', kpi_target: 'Reclami Aperti', target_verde: null, target_rosso: null, direzione: null },
  { indicatore: 'numero segnalazioni per reclami chiuse nel mese', settore: 'ISPEZIONI', calcolo: '[NUMERO SEGNALAZIONI PER RECLAMI CHIUSE NEL MESE]', kpi_target: 'Reclami Chiusi', target_verde: null, target_rosso: null, direzione: null },
  { indicatore: 'Numero totale dipendenti soggetti a formazione sicurezza', settore: 'NUMERI', calcolo: '[NUMERO TOTALE DIPENDENTI SOGGETTI A FORMAZIONE SICUREZZA]', kpi_target: 'Dipendenti Sicurezza', target_verde: null, target_rosso: null, direzione: null },
  { indicatore: 'Numero dipendenti con formazione sicurezza valida', settore: 'COMPLIANCE', calcolo: '[NUMERO DIPENDENTI CON FORMAZIONE SICUREZZA VALIDA] / [NUMERO TOTALE DIPENDENTI SOGGETTI A FORMAZIONE SICUREZZA]', kpi_target: 'Form. Sicurezza', target_verde: 0.95, target_rosso: 0.9, direzione: 'MAX' },
  { indicatore: 'Numero totale dipendenti soggetti a formazione HACCP', settore: 'NUMERI', calcolo: '[NUMERO TOTALE DIPENDENTI SOGGETTI A FORMAZIONE HACCP]', kpi_target: 'Addetti Cucina', target_verde: null, target_rosso: null, direzione: null },
  { indicatore: 'Numero dipendenti con formazione HACCP valida', settore: 'COMPLIANCE', calcolo: '[NUMERO DIPENDENTI CON FORMAZIONE HACCP VALIDA] / [NUMERO TOTALE DIPENDENTI SOGGETTI A FORMAZIONE HACCP]', kpi_target: 'Form. HACCP', target_verde: 0.95, target_rosso: 0.9, direzione: 'MAX' },
  { indicatore: 'numero incident reporting interni e near miss', settore: 'NUMERI', calcolo: '[NUMERO INCIDENT REPORTING INTERNI E NEAR MISS]', kpi_target: 'IR e Near Miss', target_verde: null, target_rosso: null, direzione: null },
  { indicatore: 'numero audit interni ricevuti (giornate) da Sede', settore: 'ISPEZIONI', calcolo: '[NUMERO AUDIT INTERNI RICEVUTI (GIORNATE) DA SEDE]', kpi_target: 'Audit Interni', target_verde: null, target_rosso: null, direzione: null },
  { indicatore: 'Numero di ispezioni ricevute da Enti esterni (ATS, NAS, ecc)', settore: 'ISPEZIONI', calcolo: '[NUMERO DI ISPEZIONI RICEVUTE DA ENTI ESTERNI (ATS, NAS, ECC)]', kpi_target: 'Ispezioni Esterne', target_verde: null, target_rosso: null, direzione: null }
];

export const KPI_SECTORS = [...new Set(KPI_RULES.map(r => r.settore))];
